name: generate animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allow manual runs
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
     
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Aman1337g
          outputs: |
            dist/images/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
